
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'instruccionesACCION DOSPUNTOS LLAVE_DER LLAVE_IZQ OPERADOR PARDER PARIZQ SENSOR SEP VALORinstrucciones : LLAVE_IZQ ACCION PARIZQ PARDER DOSPUNTOS condicion LLAVE_DERcondicion : SENSOR OPERADOR VALORinstrucciones : LLAVE_IZQ ACCION PARIZQ PARDER DOSPUNTOS horario LLAVE_DERhorario : VALOR SEP VALOR'
    
_lr_action_items = {'LLAVE_IZQ':([0,],[2,]),'$end':([1,11,12,],[0,-1,-3,]),'ACCION':([2,],[3,]),'PARIZQ':([3,],[4,]),'PARDER':([4,],[5,]),'DOSPUNTOS':([5,],[6,]),'SENSOR':([6,],[9,]),'VALOR':([6,13,14,],[10,15,16,]),'LLAVE_DER':([7,8,15,16,],[11,12,-2,-4,]),'OPERADOR':([9,],[13,]),'SEP':([10,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instrucciones':([0,],[1,]),'condicion':([6,],[7,]),'horario':([6,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instrucciones","S'",1,None,None,None),
  ('instrucciones -> LLAVE_IZQ ACCION PARIZQ PARDER DOSPUNTOS condicion LLAVE_DER','instrucciones',7,'p_instrucciones','Interprete 2.0.py',66),
  ('condicion -> SENSOR OPERADOR VALOR','condicion',3,'p_condicion','Interprete 2.0.py',79),
  ('instrucciones -> LLAVE_IZQ ACCION PARIZQ PARDER DOSPUNTOS horario LLAVE_DER','instrucciones',7,'p_instruccion_corta','Interprete 2.0.py',84),
  ('horario -> VALOR SEP VALOR','horario',3,'p_horario','Interprete 2.0.py',89),
]
